interpreters:
  goal_interpreter: # node name 
    goal:
      frame_id: map
      position:
        x: 2.4
        y: -0.04
        z: 0
      yaw: 90 # degree
    goal_action: move_base # if "None", won't use action
    wait_action: 5
    rate: 100
  velocity_interpreter: # node name 
    max_vel: 5
    rate: 100